### ISSUE TITLE
RUNTIME ERROR when doing autohack

### ISSUE THREAD

**Issue by zdt222** [ChaelCodes/bitburner-scripts#5]
RUNTIME ERROR
/scripts/autoHack.js@home

Concurrent calls to Netscript functions not allowed! Did you forget to await hack(), grow(), or some other promise-returning function? (Currently running: scp tried to run: exec)

**Comment by zdt222** [comment]
from home "run hax.js autoHack"

**Comment by pacmanninja998** [comment]
> RUNTIME ERROR /scripts/autoHack.js@home
> 
> Concurrent calls to Netscript functions not allowed! Did you forget to await hack(), grow(), or some other promise-returning function? (Currently running: scp tried to run: exec)

Having the same issue myself

**Comment by zdt222** [comment]
added a line in autoHack.js line 29 "await ns.scp" 
new error is

RUNTIME ERROR
/scripts/autoHack.js@home

Unexpected reserved word (sorry we can't be more helpful)

**Comment by ChaelCodes** [comment]
Hey! Netscript updated their API. Thank you for pointing out this issue! I have updated autoHack, if you re-import, then you should be able to run autoHack. The rest of the commands have not been updated, but I'll start updating them next week!
